# Generated by Django 3.2.10 on 2022-05-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosissummarycaries',
            old_name='diangosis_summary_teeth',
            new_name='diagnosis_summary_teeth',
        ),
        migrations.RenameField(
            model_name='diagnosissummaryteeth',
            old_name='diangosis_summary_dental',
            new_name='diagnosis_summary_dental',
        ),
    ]
